config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  resources :todos
  resources :users
  get "/signin" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true
  belongs_to :user
  def self.overdue
    all.where("due_date < ?", Date.today)
  end

  def self.due_later
    all.where("due_date > ?", Date.today)
  end

  def self.due_today
    all.where("due_date= ?", Date.today)
  end

  def self.completed
    all.where(completed: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  has_secure_password
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user != nil && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your login attempt was invalid.Please retry"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
# todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = Todo.find(id)
    render "todo"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    completed = params[:completed]
    id = params[:id]
    todo = Todo.where(user_id: current_user.id).find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.where(user_id: current_user.id).find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
    )
    if new_user.save
      redirect_to "/"
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to "/users/new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="Home-title"> Welcome to the home page</h1>

<h3 class="Home-authenticate"> 
    If you are a new user,<%= link_to "sign up here", new_user_path %> 
</h3>
<h3 class="Home-authenticate"> 
    If you are an existing user,<%= link_to "sign in here", new_session_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.first_name %>!
        <%= link_to "Sign-out",destroy_session_path,method:"delete" %>
      </p>
    <% end %>
    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <h2 class="TodoSubtitle"><%=section_title %></h2>
    <p class="TodoSectionTitle-Count"><%=todos.completed.count%>/<%=todos.count%></p>
  </div>
  <ul>
    <% todos.each do |todo| %>
    <% if(!hide_completed || !todo.completed) %>
    <li class="TodoItem">
    <label class="TodoItem-container">
    <%= form_with(url: "/todos/#{todo.id}",method:"put") do %>
    <input 
    class="TodoItem-checkbox"
    name="completed"
    type="checkbox"<%= todo.completed ? "checked" : ""%>
    onclick="this.form.submit()"
    />
    <% end %>

    <p class='<%= todo.completed ? "TodoItem-completedText" : ""%>'>
      <%= todo.todo_text %>
    </p>

    <% if show_due_date %>
      <p class="TodoItem-dueDate"><%= todo.due_date.to_s(:short) %></p>
      <% end %>

      <a href="javascript:void(0)" class="TodoItem-delete">
      <%= form_with(url: "/todos/#{todo.id}",method: "delete") do %>
         <input class="Img-Trash" type="image" src="https://cdn.iconscout.com/icon/premium/png-256-thumb/trashcan-7-624482.png">
      <% end %>
      </a>
      </label>
      </li>
      <% end %>
      <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
 <main class="TodoMain">

        <article>
            <h1 class="TodoTitle">My Todo-List</h1>
            <%= form_with(url: "/todos", method:"post",class: "AddTodo") do %>
               <%= text_field_tag 'todo_text',nil,placeholder:"What's next?",class:'AddTodo-Text' %>
               <%= date_field_tag 'due_date',nil,class:'AddTodo-Date'%>
               <%= button_tag 'Add',type:'submit', class:'AddTodo-button'%>
            <% end %>

            <%= render partial: "todo-section", locals:{
                
            section_title: "Overdue",
            todos: @todos.overdue,
            show_due_date: true,
            hide_completed: true
        
            } %>

           <%= render partial: "todo-section", locals:{
            
            section_title: "Due Today",
            todos: @todos.due_today,
            show_due_date: false,
            hide_completed: false

            
            } %>

            <%= render partial: "todo-section", locals:{
            section_title: "Due Later",
            todos: @todos.due_later,
            show_due_date: true,
            hide_completed: false
            
            } %>
        </article>

    </main>

app/views/users/new.html.erb
<p class="NewUsers-title">Welcome new user </p>
<section class="UsersNew">
    <%= form_with url:users_path do |form| %>
    <div class = "form-section">
        <p class="formInput-label">First-name:</p>
        <%= form.text_field :first_name,class:"form-input" %>
    </div>
    <div class = "form-section">
        <p class="formInput-label">Last-name:</p>
        <%= form.text_field :last_name, class:"form-input"%>
    </div>
    <div class = "form-section">
        <p class="formInput-label">Email:</p>
        <%= form.email_field :email, class:"form-input" %>
    </div>
    <div class = "form-section">
        <p class="formInput-label">Password:</p>
        <%= form.password_field :password, class:"form-input" %>
    </div>
    <div class="form-section">
        <%= form.submit "Sign-up!", class: "form-submit"%>
    </div>
<% end %> 
</section>